# Generated by Django 5.1.1 on 2025-06-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topindustry',
            name='job_growth_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topindustry',
            name='previous_job_count',
            field=models.IntegerField(default=0),
        ),
    ]
