# Generated by Django 5.1.1 on 2025-07-07 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0002_topindustry_job_growth_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industrytrend',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='topindustry',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
