# Generated by Django 5.1.1 on 2025-07-07 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend', '0003_alter_industrytrend_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='industrytrend',
            name='record_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='industrytrend',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
